IGI 1-7/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using IGI.Models;

namespace IGI.Components
{
	public class MenuViewComponent : ViewComponent
	{
		private List<MenuItem> _menuItems = new List<MenuItem>
		{
			new MenuItem{ Controller = "Home", Action = "Index", Text = "Lab 2"},
			new MenuItem{ Controller = "Product", Action = "Index", Text = "Catalog" },
			new MenuItem{ IsPage = true, Area = "Admin", Page = "/Index", Text = "Administration"}
		};

		public IViewComponentResult Invoke()
		{
			var controller = ViewContext.RouteData.Values["controller"];
			var page = ViewContext.RouteData.Values["page"];
			var area = ViewContext.RouteData.Values["area"];

			foreach (var item in _menuItems)
			{
				var _matchController = controller?.Equals(item.Controller) ?? false;
				var _matchArea = area?.Equals(item.Area) ?? false;
				if (_matchController || _matchArea)
				{
					item.Active = "active";
				}
			}

			return View(_menuItems);
		}
	}
}

IGI 1-7/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using IGI.Data;
using IGI.Extensions;
using IGI.Models;

namespace IGI.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private Cart _cart;
        private string cartKey = "cart";

        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        public IActionResult Index()
        {
            return View(_cart.Items.Values);
        }
        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            var item = _context.Parts.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

IGI 1-7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IGI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">WebLabsV06</a>
                    <div class="navbar-nav">
                        @await Component.InvokeAsync("Menu")
                    </div>

                    <partial name="_UserPartial" />

                </nav>
            </div>
        </header>
        <main class="main">
            @RenderBody()
        </main>
        <footer class="footer">
            <div class="container">
                <div class="navbar navbar-dark navbar-expand-md bg-dark">
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href="#">
                            <i class="fab fa-facebook-f fa-1.5x"></i>
                        </a>
                        <a class="nav-item nav-link" href="#">
                            <i class="fab fa-vk fa-1.5x"></i>
                        </a>
                        <a class="nav-item nav-link" href="#">
                            <i class="fab fa-twitter fa-1.5x"></i>
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IGI 1-7/Views/Shared/_ListItemPartial.cshtml
@model PCPart
<div class="col-sm-3">
    <div class='card m-2 p-1 text-center'>
        <img src="~/Images/@Model.Image"
             alt='NoImage'
             class="card-img-top" />
        <div class="card-body">
            <h5 class="card-title">
                @Model.Name
            </h5>
            <p class="card-text">
                @Model.Description
            </p>
            <div class="card-text badge badge-secondary">
                <h6>@(String.Format("{0:#,##0.00;($#,##0.00);Zero}", Model.Price)) USD</h6>
            </div> @{
                var request = ViewContext.HttpContext.Request;
                var returnUrl = request.Path + request.QueryString.ToUriComponent();
            }

            <p class="mt-2">
                <a asp-action="Add"
                   asp-controller="Cart" asp-route-id="@Model.Id" asp-route-returnUrl="@returnUrl"
                   class="btn btn-primary">
                    <i class="fa fa-shopping-cart"></i> To Cart
                </a>
            </p>
        </div>
    </div>
</div>

IGI 1-7/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using IGI.Entities;
@inject SignInManager<ApplicationUser> signInManager

@{
    ViewData["Title"] = "_UserPartial";
}

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton"
             data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
        </div>
        <div class="dropdown-menu dropdown-menu-right"
             aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">
                @*<img src="@Url.Action("GetAvatar", "Image")" width="50"
                     alt="User" class="rounded" />*@
                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" 
               asp-controller="Cart" 
               asp-action="Index">
                My goods
            </a>
            <form asp-area="Identity"
                  asp-page="/Account/Logout"
                  asp-route-returnal="@ViewContext.HttpContext.Request.Path">
                <input type="submit"
                       value="Log out"
                       class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li><a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Log in
            </a></li>
        <li><a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Register
            </a></li>

    </ul>
}